describe('Purchase tests', () => {
    it('Purchase - ok', () => {
      cy.visit('https://www.demoblaze.com')
      cy.get(':nth-child(1) > .card > :nth-child(1)').click()
      cy.get('.col-sm-12 > .btn').should("be.visible").click()
      cy.get(':nth-child(4) > .nav-link').click()
      cy.get('.col-lg-1 > .btn').click()
      cy.get('#name').invoke("val", "testName")
      cy.get('#country').invoke("val", "testCountry")
      cy.get('#city').invoke("val", "testCity")
      cy.get('#card').invoke("val", "testCard")
      cy.get('#month').invoke("val", "testMonth")
      cy.get('#year').invoke("val", "testYear")
      cy.get('#orderModal > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
      cy.get('.confirm').click()
      cy.get('#login2').should("be.visible")
    })
  })